# Raspberry Pi GPIO Broadcom pins for the SX126x LoRa HAT. 
# Set txen and rxen pin to -1 if RF module doesn't have one.
busId = 0
csId = 0
resetPin = 18
busyPin = 20
irqPin = 16
txenPin = 6
rxenPin = -1

# Set frequency to 868 Mhz.
frequency = 868000000

# Set transmit power. Default for SX126x is +22 dBm.
# Valid for transmitter only.
txPower = 22

# Modulation parameters include spreading factor (SF), bandwidth (BW),
# and coding rate (CR). Receiver must have same SF and BW settings with
# transmitter to be able to receive a LoRa packet.
spreadFactor = 9
bandwidth = 125000
codingRate = 5

# Packet parameters include header preamble length, payload length and
# CRC type. The explicit packet type is used by default and uses these
# parameters. The receiver can receive a packet with different coding
# rates and packet parameters in explicit header mode.
preambleLength = 12
payloadLength = 15
crcType = true

# LoRa message to send. If set to "temperature" the transmitter's CPU
# temperature will be sent in the payload.
message = "HeLoRa World!\0"
#message = "temperature"

# Interval in seconds between transmitter sending LoRa messages.
sleepTime = 5
